config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
    resources :comments
  end

  resource :profile, only: [:show, :edit, :update]
  resources :site_configurations
  root 'articles#index',  as: :home

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  scope :highlighted, -> { where(highlight: true)}
  scope :recent, -> {where(highlight: false)}

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 1}
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  attr_reader :full_name

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/site_configuration.rb
class SiteConfiguration < ApplicationRecord
  belongs_to :user

  def settings_hash
    JSON.parse(settings, symbolize_names: true) if settings
  end

  def self.cms
    find_by key: 'cms'
  end

  def self.settings_hash(site_config)
    JSON.parse(site_config.settings, symbolize_names: true) if site_config
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.recent
    @highlighted_articles = Article.highlighted
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end

  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :highlight)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article

  def create
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def edit
    @comment = @article.comments.find(params[:id])
    render 'articles/show'

  end

  def update
    @comment = @article.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to article_path(@article)
    end

  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = profile
  end

  def edit
    @profile = profile
  end

  def update
    if profile.update(profile_params)
      redirect_to profile_path
    else
      render 'edit'
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :bio)
  end

  def profile
    @user ||=  SiteConfiguration.cms.try(:user)
    if @user
      @user.profile ? @user.profile : @user.create_profile
    else
      nil
    end
  end
end

app/controllers/site_configurations_controller.rb
class SiteConfigurationsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user?
  before_action :set_site_configuration, only: [:show, :edit, :update ]

  def index
    @site_configurations = SiteConfiguration.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
    if @site_configuration.update(site_configuration_params)
      redirect_to @site_configuration
    else
      render 'edit'
    end
  end

  def destroy
  end

  private
  def admin_user?
    current_user.try(:admin?)
  end

  def site_configuration_params
    settings_params = params.require(:site_configuration).permit(settings: {})
    settings_params = settings_params.merge(settings: settings_params[:settings].to_json)
  end

  def set_site_configuration
    @site_configuration = SiteConfiguration.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/site_configurations_helper.rb
module SiteConfigurationsHelper
end

app/views/articles/_article.html.erb
<section class="post" id="article_<%= article.id %>">
    <header class="post-header">
      <img width="48" height="48" alt="Carlos&#x27;s avatar" class="post-avatar"
        src="https://secure.gravatar.com/avatar/9f22a8f13769b4ad434bbf5694d9b718?s=100&d=identicon&r=g">

        <h2 class="post-title"><%= link_to article.title, article_path(article) %></h2>

        <p class="post-meta">
            By <a href="#" class="post-author">Carlos Gabaldon</a> under
            <a class="post-category post-category-design" href="#">CSS</a>
            <a class="post-category post-category-pure" href="#">Pure</a>
        </p>
    </header>

    <div class="post-description">
        <p>
          <%= article.text[0..100] %>..
        </p>
        <p><%= link_to 'Edit', edit_article_path(article) if user_signed_in? %></p>
    </div>
</section>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>

<% if @article.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@article.errors.count, "error") %> prohibited
       this article from being saved:
     </h2>
     <ul>
       <% @article.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
  <% end %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br/>
    <%= f.text_area :text %><br/>
  </p>

  <p>
    <%= f.label :highlight %><br/>
    <%= f.check_box :highlight %><br/>
  </p>

  <p>
    <%= f.submit %> <%= link_to 'Cancel', articles_path %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<!-- highlighted articles -->
<% if @highlighted_articles.length > 0 %>
  <div class="posts">
      <h1 class="content-subhead">Highlighed Articles</h1>
      <% @highlighted_articles.reverse_each do |article| %>
        <%= render article %>
    <% end %>
  </div>
<% end %>


<!-- all articles -->
<div class="posts">
  <h1 class="content-subhead">Recent Articles</h1>
  <% @articles.reverse_each do |article| %>
      <%= render article %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.text %></p>

<h2>Comments</h2>
<div id='comments-section'>
  <%= render @article.comments %>
</div>

<div id='comment-section'>
  <% if user_signed_in? %>
    <% if @comment %>
      <h2>Edit comment</h2>
      <%= render partial: 'comments/form', locals: {comment: @comment} %>
    <% else %>
      <h2>Add a comment</h2>
      <%= render partial: 'comments/form', locals: {comment: @article.comments.build} %>
    <% end %>
  <% end %>
</div>

<div id='user-section'>
  <%= link_to 'Edit', edit_article_path if user_signed_in? %>
  <%= link_to 'Articles', articles_path %>
</div>

<div id='admin-section'>
  <% if current_user.try(:admin?) %>
    <h3>Danger Zone</h3>
    <p>
      <%= link_to 'Delete', article_path(@article),
          method: :delete, data: { confirm: 'Are you sure, this can not be undone?'} %>
    </p>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>">
  <p>
    <%= comment.commenter %>
  </p>

  <p>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to 'Edit', edit_article_comment_path(comment.article, comment) if user_signed_in? %>
    <%= link_to 'Delete', [comment.article, comment], method: :delete,
                data: { confirm: 'Are you sure?'}  if current_user.try(:admin?) %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, comment]) do |f| %>
<p>
  <%= f.text_field :commenter, value: current_user.email, readonly: true  %>
</p>
<p>
  <%= f.label :body %><br/>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.">

    <!-- Start Pure CSS (https://purecss.io) -->
  <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.2/build/pure-min.css"
    integrity="sha384-UQiGfs9ICog+LwheBSRCt1o5cbyKIHbwjWscjemyBMT9YCUMZffs6UqUTd0hObXD"
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.2/build/grids-responsive-min.css">
    <!-- End Pure CSS -->

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="layout" class="pure-g">

      <div class="sidebar pure-u-1 pure-u-md-1-4">
          <div class="header">
              <h1 class="brand-title"><%= SiteConfiguration.settings_hash(SiteConfiguration.cms)[:title] if SiteConfiguration.cms %></h1>
              <h2 class="brand-tagline"><%= SiteConfiguration.settings_hash(SiteConfiguration.cms)[:tagline] if SiteConfiguration.cms %></h2>

              <nav class="nav">
                  <ul class="nav-list">
                      <li class="nav-item">
                          <%= link_to 'Articles', articles_path, class: 'pure-button' %>
                      </li>
                      <li class="nav-item">
                        <% if user_signed_in? %>
                          <%= link_to 'New Article', new_article_path,
                            class: 'pure-button' %>
                        <% end %>
                        </li>
                      </li>
                      <li class="nav-item">
                          <%= link_to 'About', profile_path, class: 'pure-button' %>
                      </li>
                      <% if user_signed_in? && current_user.try(:admin?) %>
                        <li class="nav-item">
                            <%= link_to 'Configure Site', site_configurations_path, class: 'pure-button' %>
                        </li>
                      <% end %>
                      <li class="nav-item">
                          <% if user_signed_in? %>
                            <%= link_to 'Log out', destroy_user_session_path,
                              class: 'pure-button', method: :delete %>
                          <% else %>
                            <%= link_to 'Log in', new_user_session_path,
                              class: 'pure-button' %>
                          <% end %>
                      </li>
                  </ul>
              </nav>
          </div>
      </div>

      <div class="content pure-u-1 pure-u-md-3-4">
        <div>
          <% if flash[:notice] %>
            <div class="notice"><%= flash[:notice] %></div>
          <% end %>

          <% if flash[:alert] %>
            <div class="alert"><%= flash[:alert] %></div>
          <% end %>

          <%= yield %>

          <div class="footer">
              <div class="pure-menu pure-menu-horizontal">
                  <ul>
                      <li class="pure-menu-item"><a href="http://carlosgabaldon.com" class="pure-menu-link" target="_new">About</a></li>
                      <li class="pure-menu-item"><a href="https://www.linkedin.com/in/carlosgabaldon/" class="pure-menu-link" target="_new">LinkedIn</a></li>
                      <li class="pure-menu-item"><a href="https://github.com/CarlosGabaldon" class="pure-menu-link" target="_new">GitHub</a></li>
                  </ul>
              </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>

<% if @profile.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@profile.errors.count, "error") %> prohibited
       this article from being saved:
     </h2>
     <ul>
       <% @profile.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
  <% end %>

  <p>
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %><br/>
  </p>

  <p>
    <%= f.label :bio %><br/>
    <%= f.text_area :bio %><br/>
  </p>

  <p>
    <%= f.submit %> <%= link_to 'Cancel', profile_path %>
  </p>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' if @profile %>

app/views/profiles/show.html.erb
<span><%= link_to 'Edit your profile', edit_profile_path if signed_in? && current_user.try(:admin?) %></span>
<% if @profile %>
  <h1><%= @profile.full_name %></h1>
  <div>
    <%= @profile.bio.try(:html_safe) %>

<% else %>
  <span>No profile defined..</span>

<% end %>

app/views/site_configurations/create.html.erb
<h1>SiteConfigurations#create</h1>
<p>Find me in app/views/site_configurations/create.html.erb</p>

app/views/site_configurations/destroy.html.erb
<h1>SiteConfigurations#destroy</h1>
<p>Find me in app/views/site_configurations/destroy.html.erb</p>

app/views/site_configurations/edit.html.erb
<h1>Edit <%=@site_configuration.key %></h1>

<%= form_for(@site_configuration) do |f| %>
  <% if @site_configuration.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@profile.errors.count, "error") %> prohibited
         this article from being saved:
       </h2>
       <ul>
         <% @site_configuration.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
  <% end %>

  <%= f.fields_for :settings do |settings_fields| %>
    <% @site_configuration.settings_hash.each do |k, v| %>
      <%= settings_fields.label k %>
      <%= settings_fields.text_field k, value: v %>
    <% end %>
  <% end %>

  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', site_configuration_path(@site_configuration) %>
  </p>

<% end %>

app/views/site_configurations/index.html.erb
<h1>Configure Site</h1>
<% @site_configurations.each do |site_configuration| %>
  <h2 class="post-title"><%= link_to site_configuration.key, site_configuration_path(site_configuration) %> </h2>
<% end %>

app/views/site_configurations/new.html.erb
<h1>SiteConfigurations#new</h1>
<p>Find me in app/views/site_configurations/new.html.erb</p>

app/views/site_configurations/show.html.erb
<h1><%= @site_configuration.key %> </h1>

<h3>Settings</h3>
<span><%= link_to 'Edit', edit_site_configuration_path(@site_configuration) if current_user.try(:admin?) %>
<% SiteConfiguration.settings_hash(@site_configuration).each do |setting, value| %>
  <p><%= setting %>: <%= value %></p>
<% end %>

app/views/site_configurations/update.html.erb
<h1>SiteConfigurations#update</h1>
<p>Find me in app/views/site_configurations/update.html.erb</p>